import { mount, flushPromises } from '@vue/test-utils'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { reactive } from 'vue'
import ConnectView from '../ConnectView.vue'
import ConsoleView from '../ConsoleView.vue'

const api = vi.hoisted(() => ({ list:vi.fn(), groups:vi.fn(), create:vi.fn(), toggle:vi.fn(), stats:vi.fn(), usage:vi.fn() }))
const route = reactive({path:'/keys'})
vi.mock('vue-router',()=>({useRoute:()=>route}))
vi.mock('@/stores/auth',()=>({useAuthStore:()=>({user:{balance:12},isAuthenticated:true})}))
vi.mock('@/api/keys',()=>({keysAPI:{list:api.list,create:api.create,toggleStatus:api.toggle}}))
vi.mock('@/api/groups',()=>({userGroupsAPI:{getAvailable:api.groups}}))
vi.mock('@/api/usage',()=>({usageAPI:{getDashboardStats:api.stats,list:api.usage}}))
const global = { stubs:{Sup3APIShell:{template:'<div><slot /></div>'},RouterLink:{template:'<a><slot /></a>'}} }
beforeEach(()=>{vi.clearAllMocks();route.path='/keys'})

describe('Sup3API customer portal',()=>{
  it('loads real dashboard statistics without fetching or creating keys',async()=>{
    route.path='/dashboard'
    api.stats.mockResolvedValue({active_api_keys:3,today_requests:12})
    const wrapper=mount(ConsoleView,{global});await flushPromises()
    expect(wrapper.text()).toContain('3')
    expect(api.stats).toHaveBeenCalledOnce()
    expect(api.list).not.toHaveBeenCalled()
    expect(api.create).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it('only sends explicit diagnostics to same-origin endpoints, never inserts keys into snippets',async()=>{
    const fetch=vi.fn().mockResolvedValue({ok:true,headers:new Headers({'content-type':'application/json'}),json:async()=>({providers:[]})})
    vi.stubGlobal('fetch',fetch)
    const wrapper=mount(ConnectView,{global})
    expect(fetch).not.toHaveBeenCalled()
    await wrapper.findAll('button').find(b=>b.text()==='Meshy · 3D')!.trigger('click')
    await wrapper.find('input[type="password"]').setValue('private-key-not-for-examples')
    expect(wrapper.find('pre').text()).not.toContain('private-key-not-for-examples')
    await wrapper.findAll('button').find(b=>b.text()==='查询资产能力')!.trigger('click');await flushPromises()
    expect(fetch).toHaveBeenCalledWith('/v1/assets/capabilities',expect.objectContaining({method:'GET',credentials:'omit'}))
    await wrapper.findAll('button').find(b=>b.text()==='校验与估价')!.trigger('click');await flushPromises()
    expect(fetch).toHaveBeenLastCalledWith('/v1/assets/quotes',expect.objectContaining({method:'POST'}))
    expect(fetch.mock.calls.some(([url])=>url==='/v1/assets/jobs')).toBe(false)
    wrapper.unmount();vi.unstubAllGlobals()
  })
  it('keeps native workflows separate and fixes unsupported operation on provider switch',async()=>{
    const fetch=vi.fn();vi.stubGlobal('fetch',fetch)
    const wrapper=mount(ConnectView,{global})
    await wrapper.findAll('button').find(b=>b.text()==='Meshy · 3D')!.trigger('click')
    expect(wrapper.find('select').findAll('option').map(o=>o.text())).toEqual(['统一 API','Tripo 原生 API','Meshy 原生 API'])
    expect(wrapper.find('details').attributes('open')).toBeUndefined()
    await wrapper.find('select').setValue('native-meshy')
    await wrapper.findAll('select')[1]!.setValue('refine')
    expect(wrapper.find('pre').text()).toContain('/providers/meshy/openapi/v2/text-to-3d')
    expect(wrapper.find('pre').text()).toContain('preview_task_id')
    expect(wrapper.text()).not.toContain('校验与估价')
    await wrapper.find('textarea').setValue('{"mode":"refine","preview_task_id":"owned-id","new_feature":true}')
    expect(wrapper.find('pre').text()).toContain('new_feature')
    expect(wrapper.find('pre').text()).not.toContain('"payload"')
    await wrapper.find('select').setValue('native-tripo')
    expect((wrapper.findAll('select')[1]!.element as HTMLSelectElement).value).toBe('text_to_3d')
    expect(wrapper.find('pre').text()).toContain('/providers/tripo/v3/generation/text-to-model')
    await wrapper.find('textarea').setValue('{')
    expect(wrapper.find('[role="alert"]').text()).toContain('有效 JSON')
    await wrapper.find('select').setValue('unified')
    expect(wrapper.find('pre').text()).toContain('/v1/assets/jobs')
    expect(wrapper.find('pre').text()).not.toContain('preview_task_id')
    expect(fetch).not.toHaveBeenCalled()
    wrapper.unmount();vi.unstubAllGlobals()
  })
  it('preserves output constraints across providers and offers an explicit portable reset',async()=>{
    const wrapper=mount(ConnectView,{global})
    await wrapper.findAll('button').find(b=>b.text()==='Meshy · 3D')!.trigger('click')
    await wrapper.find('input[value="fbx"]').setValue(true)
    expect(wrapper.find('pre').text()).toContain('"fbx"')
    await wrapper.findAll('button').find(b=>b.text()==='Tripo · 3D')!.trigger('click')
    expect(wrapper.find('[role="alert"]').text()).toContain('交付格式')
    expect(wrapper.find('pre').text()).toContain('"fbx"')
    await wrapper.findAll('button').find(b=>b.text()==='改用通用 GLB 格式')!.trigger('click')
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(wrapper.find('pre').text()).not.toContain('"fbx"')
    wrapper.unmount()
  })

})
